[package]
name = "import"
version = "0.1.0"
edition = "2021"

[dependencies]
figment = { version = "0.10.19", features = [ "env", "toml" ] }
serde = { version = "1.0.211", features = [ "derive" ] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
